Repository 4pforp/4p-Market, pull requests merged in 2022-07, with the labels that each got.

#27 🎨 버튼 css background-color로 변경
  src/Pages/logIn/EmailLogin.scss
  src/Pages/signUp/button/button.scss
  src/Pages/signUp/emailSignUp/EmailSignUP.jsx
  src/Pages/signUp/emailSignUp/emailSignUp.scss
Labels: css

#29 소셜로그인 버튼구현을 프로퍼티를 사용하는 방식으로 수정했습니다.
  src/Pages/logIn/FacebookBtn.jsx
  src/Pages/logIn/FacebookBtn.scss
  src/Pages/logIn/GoogleBtn.jsx
  src/Pages/logIn/GoogleBtn.scss
  src/Pages/logIn/KakaoBtn.jsx
  src/Pages/logIn/KakaoBtn.scss
  src/Pages/logIn/LoginSection.jsx
  src/Pages/logIn/SocialLoginBtn.jsx
  src/Pages/logIn/SocialLoginBtn.scss
Labels: refactoring, css, React

#30 ♻️ 마크업 통일되게 수정, 전체폴더 구조 개선
  src/App.jsx
  src/App.scss
  src/Components/button/SocialLoginBtn.jsx
  src/Components/button/SocialLoginBtn.scss
  src/Components/splash/Splash.jsx
  src/Components/splash/Splash.scss
  src/Components/style/_font.scss
  src/Components/style/_variables.scss
  src/Components/style/default.scss
  src/Components/style/reset.scss
  src/Pages/emailLogin/EmailLogin.jsx
  src/Pages/emailLogin/EmailLogin.scss
  src/Pages/feedPage/FeedPage.jsx
  src/Pages/feedPage/FeedPage.scss
  src/Pages/homePage/HomePage.jsx
  src/Pages/homePage/HomePage.scss
  src/Pages/logInPage/LoginPage.jsx
  src/Pages/logInPage/LoginPage.scss
  src/Pages/logInPage/LoginSection.jsx
  src/Pages/logInPage/LoginSection.scss
  src/Pages/logInPage/UserAccount.jsx
  src/Pages/logInPage/UserAccount.scss
  src/Pages/signUp/Button.jsx
  src/Pages/signUp/Button.scss
  src/Pages/signUp/UserContext.jsx
  src/Pages/signUp/emailSignUp/EmailSignUP.jsx
  src/Pages/signUp/profileSet/ProfileSet.jsx
  src/Pages/signUp/profileSet/profileSet.scss
  src/Pages/signUp/signUp.jsx
  src/Pages/signUp/signUp.scss
  src/assets/L-button.svg
  src/assets/L-disabled-button.svg
  src/assets/L-profile.svg
  src/assets/facebook-logo.svg
  src/assets/full-logo.svg
  src/assets/google-logo.svg
  src/assets/home-logo.svg
  src/assets/icon-picture.svg
  src/assets/kakao-logo.svg
  src/assets/symbol-logo-W.svg
  src/assets/upload-file.svg
Labels: refactoring, cleanup, Html, css, React

#31 📝 추가될 기능의 파일 생성, 라우트 작업
  src/App.jsx
  src/Components/footer/MainFooter.jsx
  src/Components/header/MainHeader.jsx
  src/Components/header/PostHeader.jsx
  src/Pages/chat/Chat.jsx
  src/Pages/feedPage/FeedPage.jsx
  src/Pages/feedPage/FeedPage.scss
  src/Pages/home/Home.jsx
  src/Pages/homePage/HomePage.jsx
  src/Pages/homePage/HomePage.scss
  src/Pages/logIn/Login.jsx
  src/Pages/logIn/Login.scss
  src/Pages/logIn/LoginSection.jsx
  src/Pages/logIn/LoginSection.scss
  src/Pages/logIn/UserAccount.jsx
  src/Pages/logIn/UserAccount.scss
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/emailLogin/EmailLogin.scss
  src/Pages/logIn/signUp/Button.jsx
  src/Pages/logIn/signUp/Button.scss
  src/Pages/logIn/signUp/SignUp.jsx
  src/Pages/logIn/signUp/SignUp.scss
  src/Pages/logIn/signUp/UserContext.jsx
  src/Pages/logIn/signUp/emailSignUp/EmailSignUP.jsx
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/Pages/logIn/signUp/profileSet/profileSet.scss
  src/Pages/post/Post.jsx
  src/Pages/product/Product.jsx
  src/Pages/profile/Profile.jsx
  src/Pages/profileEdit/ProfileEdit.jsx
Labels: docs

#32 🔧 회원가입 유효성 검사 기능 추가, 함수 이름, 클래스 이름 변경
  src/App.jsx
  src/Pages/LoginContext.jsx
  src/Pages/home/Home.jsx
  src/Pages/logIn/signUp/Button.jsx
  src/Pages/logIn/signUp/Button.scss
  src/Pages/logIn/signUp/SignUp.jsx
  src/Pages/logIn/signUp/SignUp.scss
  src/Pages/logIn/signUp/UserContext.jsx
  src/Pages/logIn/signUp/emailSignUp/EmailSignUP.jsx
  src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
  src/Pages/logIn/signUp/emailSignUp/SetAccount.jsx
  src/Pages/logIn/signUp/profileSet/EditInfo.jsx
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/Pages/logIn/signUp/profileSet/UploadPic.jsx
  src/Pages/logIn/signUp/profileSet/profileSet.scss
Labels: refactoring, function

#34 🔧 회원가입 계정 검증 기능 추가
  src/Components/splash/Splash.jsx
  src/Pages/logIn/signUp/SignUp.scss
  src/Pages/logIn/signUp/emailSignUp/SetAccount.jsx
  src/Pages/logIn/signUp/profileSet/EditInfo.jsx
  src/Pages/logIn/signUp/profileSet/UploadPic.jsx
  src/Pages/logIn/signUp/profileSet/profileSet.scss
Labels: function, React

#33 라우트 v6로 업그레이드 및 코드수정, Splash 애니메이션효과 추가
  package-lock.json
  package.json
  src/App.jsx
  src/Components/splash/Splash.jsx
  src/Components/splash/Splash.scss
  src/Pages/logIn/emailLogin/EmailLogin.jsx
Labels: refactoring, css, React

#35 🧹 스타일 코드 경로, 라우터, 오류 코드 변경
  src/App.jsx
  src/Pages/home/Home.jsx
  src/Pages/home/Home.scss
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/emailLogin/EmailLogin.scss
  src/Pages/logIn/signUp/SignUp.jsx
  src/Pages/logIn/signUp/SignUp.scss
Labels: fix

#36 🔧로그인페이지 추가 기능 구현 및 리팩토링
  src/Pages/logIn/emailLogin/Button.scss
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/emailLogin/EmailLogin.scss
Labels: refactoring, function, css, React

#39 ♻️ 로그인 회원가입페이지 버튼 컴포넌트화
  src/Pages/logIn/Button.jsx
  src/Pages/logIn/Button.scss
  src/Pages/logIn/emailLogin/EmailLogin.scss
  src/Pages/logIn/signUp/SignUp.scss
  src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
Labels: refactoring, css, React

#40 NavBar UI 구현 및 각 페이지에 맞는 NavBar 배치
  src/App.scss
  src/Components/button/BackBtn.jsx
  src/Components/button/BackBtn.scss
  src/Components/button/MoreBtn.jsx
  src/Components/button/MoreBtn.scss
  src/Components/button/SaveBtn.jsx
  src/Components/button/SaveBtn.scss
  src/Components/button/SearchBtn.jsx
  src/Components/button/SearchBtn.scss
  src/Components/header/MainHeader.jsx
  src/Components/header/PostHeader.jsx
  src/Components/navBar/BasicNav.jsx
  src/Components/navBar/MainNav.jsx
  src/Components/navBar/MainNav.scss
  src/Components/navBar/SaveNav.jsx
  src/Components/navBar/SearchNav.jsx
  src/Components/navBar/SearchNav.scss
  src/Components/navBar/UploadNav.jsx
  src/Components/style/_variables.scss
  src/Pages/chat/Chat.jsx
  src/Pages/home/Home.jsx
  src/Pages/logIn/Login.jsx
  src/Pages/logIn/LoginSection.jsx
  src/Pages/logIn/signUp/profileSet/profileSet.scss
  src/Pages/post/Post.jsx
  src/Pages/product/Product.jsx
  src/Pages/profile/Profile.jsx
  src/Pages/profileEdit/ProfileEdit.jsx
  src/assets/icon-arrow-left.svg
  src/assets/icon-more-vertical.svg
  src/assets/icon-search.svg
Labels: css, React

#41 회원가입 오류 수정, 프로필 사진 기본 설정 기능 추가
  src/Pages/logIn/Button.jsx
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/signUp/Button.jsx
  src/Pages/logIn/signUp/Button.scss
  src/Pages/logIn/signUp/SignUp.jsx
  src/Pages/logIn/signUp/SignUp.scss
  src/Pages/logIn/signUp/emailSignUp/EditAccount.jsx
  src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
  src/Pages/logIn/signUp/profileSet/EditInfo.jsx
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/Pages/logIn/signUp/profileSet/UploadPic.jsx
Labels: fix, function

#44 🧹 isLogin 로컬스토리지와 연동하여 로그인 유지 기능 추가 #43
  src/App.jsx
  src/Pages/LoginContext.jsx
  src/Pages/home/Home.jsx
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/signUp/SignUp.jsx
  src/Pages/logIn/signUp/profileSet/UploadPic.jsx
  src/Pages/logIn/signUp/profileSet/profileSet.scss
Labels: cleanup, function

#47 Footer UI 추가 및 수정, Footer 사용이미지 추가, 채팅방경로추가
  src/App.jsx
  src/Components/button/UploadIconBtn.jsx
  src/Components/footer/ChatroomFooter.jsx
  src/Components/footer/CommentFooter.jsx
  src/Components/footer/MainFooter.jsx
  src/Components/footer/MainFooter.scss
  src/Components/footer/PageFooter.scss
  src/Components/footer/TabmenuList.jsx
  src/Components/footer/TabmenuList.scss
  src/Components/style/_variables.scss
  src/Pages/chat/Chat.jsx
  src/Pages/chat/ChatRoom.jsx
  src/Pages/post/Post.jsx
  src/assets/icon-edit.svg
  src/assets/icon-home-fill.svg
  src/assets/icon-home.svg
  src/assets/icon-message-circle-fill.svg
  src/assets/icon-message-circle.svg
  src/assets/icon-profile-small.svg
  src/assets/icon-user-fill.svg
  src/assets/icon-user.svg
  src/assets/upload-file-gray.svg
Labels: Html, css, React

#50 ♻️ 로그인 후 스플레시 페이지 구현 , 버튼 속성명 변경
  src/Pages/logIn/Button.jsx
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
Labels: refactoring, cleanup

#51 footer 스타일 수정 및 하단 탭 활성화 기능 추가
  src/Components/footer/ChatroomFooter.jsx
  src/Components/footer/CommentFooter.jsx
  src/Components/footer/MainFooter.scss
  src/Components/footer/PageFooter.scss
  src/Components/footer/TabmenuList.jsx
  src/Components/footer/TabmenuList.scss
Labels: function, css, React

#53 🎨 채팅 ui 구현
  src/Components/navBar/ChatRoomNav.jsx
  src/Components/navBar/FollowNav.jsx
  src/Components/navBar/InfoNav.scss
  src/Components/style/reset.scss
  src/Pages/chat/Chat.jsx
  src/Pages/chat/ChatRoom.jsx
  src/Pages/chat/chatPage/ChatItem.jsx
  src/Pages/chat/chatPage/ChatItem.scss
  src/Pages/chat/chatPage/ChatPage.jsx
  src/Pages/chat/chatPage/ChatPage.scss
  src/Pages/chat/chatRoom/ChatRoom.jsx
  src/Pages/chat/chatRoom/ChatRoom.scss
  src/Pages/chat/chatRoom/Chatting.jsx
  src/Pages/chat/chatRoom/GetMessage.jsx
  src/Pages/chat/chatRoom/Message.scss
  src/Pages/chat/chatRoom/SendMessage.jsx
Labels: css, React

#58 🎨 follower following 페이지 ui 구현
  src/App.scss
  src/Components/button/FollowBtn.jsx
  src/Components/button/FollowBtn.scss
  src/Components/button/SaveBtn.jsx
  src/Components/button/SaveBtn.scss
  src/Components/header/ChatRoomHeader.jsx
  src/Components/header/CommonHeader.jsx
  src/Components/header/FollowHeader.jsx
  src/Components/header/Header.scss
  src/Components/header/MainHeader.jsx
  src/Components/header/SaveHeader.jsx
  src/Components/header/SearchHeader.jsx
  src/Components/header/SearchHeader.scss
  src/Components/header/UploadHeader.jsx
  src/Components/style/_variables.scss
  src/Components/style/default.scss
  src/Components/style/reset.scss
  src/Pages/chat/chatPage/ChatItem.scss
  src/Pages/chat/chatPage/ChatPage.jsx
  src/Pages/chat/chatPage/ChatPage.scss
  src/Pages/chat/chatRoom/ChatRoom.jsx
  src/Pages/chat/chatRoom/GetMessage.jsx
  src/Pages/chat/chatRoom/SendMessage.jsx
  src/Pages/follow/Follow.scss
  src/Pages/follow/FollowUser.jsx
  src/Pages/follow/Followers.jsx
  src/Pages/follow/Followings.jsx
  src/Pages/home/Home.jsx
  src/Pages/home/userSearch/UserSearch.jsx
  src/Pages/post/Post.jsx
  src/Pages/product/Product.jsx
  src/Pages/profile/Profile.jsx
  src/Pages/profileEdit/ProfileEdit.jsx
Labels: refactoring, css, React

#61 🎨: ProfileEdit, Product UI 구현
  src/Pages/product/Product.jsx
  src/Pages/product/Product.scss
  src/Pages/profileEdit/ProfileEdit.jsx
  src/Pages/profileEdit/ProfileEdit.scss
Labels: Html, css, React

#57 🎨 유저 검색 화면 및 게시글 댓글 페이지 화면 구현
  src/App.jsx
  src/Components/button/CommentBtn.jsx
  src/Components/button/CommentBtn.scss
  src/Components/button/LikeBtn.jsx
  src/Components/button/LikeBtn.scss
  src/Components/button/UserMoreBtn.jsx
  src/Components/button/UserMoreBtn.scss
  src/Components/style/_variables.scss
  src/Pages/home/userSearch/SearchResult.jsx
  src/Pages/home/userSearch/SearchResult.scss
  src/Pages/home/userSearch/UserSearch.jsx
  src/Pages/profile/commentPage/CommentList.jsx
  src/Pages/profile/commentPage/CommentList.scss
  src/Pages/profile/commentPage/CommentPage.jsx
  src/Pages/profile/commentPage/CommentPage.scss
  src/assets/example-picture.jpg
  src/assets/icon-heart-fill.svg
Labels: css, React

#64 🧹comment/like/more 버튼 classname 수정
  src/Components/button/CommentBtn.jsx
  src/Components/button/CommentBtn.scss
  src/Components/button/LikeBtn.jsx
  src/Components/button/LikeBtn.scss
Labels: cleanup

#68 UploadPost페이지 UI 구현 및 충돌해결
  src/App.jsx
  src/Components/button/CommentBtn.jsx
  src/Components/button/CommentBtn.scss
  src/Components/footer/MainFooter.jsx
  src/Components/footer/MainFooter.scss
  src/Components/footer/TabmenuList.scss
  src/Components/style/reset.scss
  src/Pages/post/UploadPost.jsx
  src/Pages/post/UploadPost.scss
  src/Pages/profileEdit/ProfileEdit.scss
Labels: fix, css, React

#71 🔧 로그인 여부에 따른 라우팅 접근제한 기능 추가, css 컨벤션 코드 수정
  src/App.jsx
  src/App.scss
  src/Components/button/SocialLoginBtn.jsx
  src/Components/button/SocialLoginBtn.scss
  src/Components/post/Post.jsx
  src/Pages/logIn/Button.jsx
  src/Pages/logIn/Button.scss
  src/Pages/logIn/Login.jsx
  src/Pages/logIn/Login.scss
  src/Pages/logIn/LoginSection.jsx
  src/Pages/logIn/LoginSection.scss
  src/Pages/logIn/UserAccount.jsx
  src/Pages/logIn/UserAccount.scss
  src/Pages/logIn/emailLogin/EmailLogin.jsx
  src/Pages/logIn/emailLogin/EmailLogin.scss
  src/Pages/logIn/signUp/SignUp.scss
  src/Pages/logIn/signUp/emailSignUp/EditAccount.jsx
  src/Pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
  src/Pages/logIn/signUp/profileSet/EditInfo.jsx
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/Pages/logIn/signUp/profileSet/UploadPic.jsx
  src/Pages/logIn/signUp/profileSet/profileSet.scss
  src/Pages/profile/profileHeader/ProfileHeader.jsx
  src/Pages/profile/profileHeader/ProfileHeader.scss
  src/Pages/profile/userPost/UserPost.jsx
  src/Pages/profile/userProduct/Product.jsx
  src/Pages/profile/userProduct/UserProduct.jsx
  src/Pages/profile/userProduct/UserProduct.scss
Labels: refactoring, cleanup

#72 컨벤션에 맞게 코드 수정 및 uploadPost 폴더 생성과 경로 변경
  src/App.jsx
  src/Components/button/CommentBtn.jsx
  src/Components/button/CommentBtn.scss
  src/Components/button/EditProfileBtn.jsx
  src/Components/button/LikeBtn.jsx
  src/Components/button/LikeBtn.scss
  src/Components/button/PostProductBtn.jsx
  src/Components/button/ProfileButton.scss
  src/Components/button/UploadIconBtn.jsx
  src/Components/button/UploadProductBtn.jsx
  src/Components/button/UserMoreBtn.scss
  src/Components/footer/ChatroomFooter.jsx
  src/Components/footer/CommentFooter.jsx
  src/Components/footer/MainFooter.jsx
  src/Components/footer/MainFooter.scss
  src/Components/footer/PageFooter.scss
  src/Components/footer/TabmenuList.jsx
  src/Components/footer/TabmenuList.scss
  src/Components/navBar/BasicNav.jsx
  src/Components/navBar/ChatRoomNav.jsx
  src/Components/navBar/FollowNav.jsx
  src/Components/navBar/InfoNav.scss
  src/Components/navBar/MainNav.jsx
  src/Components/navBar/MainNav.scss
  src/Components/navBar/SaveNav.jsx
  src/Components/navBar/SearchNav.jsx
  src/Components/navBar/SearchNav.scss
  src/Components/navBar/UploadNav.jsx
  src/Components/post/Post.jsx
  src/Components/post/Post.scss
  src/Components/splash/Splash.jsx
  src/Components/splash/Splash.scss
  src/Components/style/reset.scss
  src/Pages/post/Post.jsx
  src/Pages/product/Product.jsx
  src/Pages/product/Product.scss
  src/Pages/product/ProductInput.jsx
  src/Pages/profile/MyProfile.jsx
  src/Pages/profile/Profile.scss
  src/Pages/profile/UserProfile.jsx
  src/Pages/profile/commentPage/CommentList.scss
  src/Pages/profile/commentPage/CommentPage.jsx
  src/Pages/profile/commentPage/CommentPage.scss
  src/Pages/profile/profileHeader/ProfileHeader.jsx
  src/Pages/profile/profileHeader/ProfileHeader.scss
  src/Pages/profile/userPost/UserPost.jsx
  src/Pages/profile/userPost/UserPost.scss
  src/Pages/profile/userProduct/Product.jsx
  src/Pages/profile/userProduct/UserProduct.jsx
  src/Pages/profile/userProduct/UserProduct.scss
  src/Pages/profileEdit/ProfileEdit.scss
  src/Pages/uploadPost/UploadPost.jsx
  src/Pages/uploadPost/UploadPost.scss
  src/assets/icon-post-album-off.svg
  src/assets/icon-post-album-on.svg
  src/assets/icon-post-list-off.svg
  src/assets/icon-post-list-on.svg
Labels: Html, css

#73 컨벤션에 맞게 코드수정
  src/App.jsx
  src/Components/button/UploadIconBtn.jsx
  src/Components/footer/ChatroomFooter.jsx
  src/Components/footer/CommentFooter.jsx
  src/Components/footer/MainFooter.jsx
  src/Components/footer/MainFooter.scss
  src/Components/footer/PageFooter.scss
  src/Components/footer/TabmenuList.jsx
  src/Components/footer/TabmenuList.scss
  src/Components/splash/Splash.jsx
  src/Components/splash/Splash.scss
  src/Pages/product/Product.jsx
  src/Pages/product/Product.scss
  src/Pages/product/ProductInput.jsx
  src/Pages/uploadPost/UploadPost.jsx
  src/Pages/uploadPost/UploadPost.scss
Labels: Html, css

#75 HTML , CSS 컨벤션 적용
  src/App.jsx
  src/Components/button/FollowBtn.jsx
  src/Components/button/FollowBtn.scss
  src/Components/splash/Splash.scss
  src/Pages/chat/chatPage/ChatItem.jsx
  src/Pages/chat/chatPage/ChatItem.scss
  src/Pages/chat/chatPage/ChatPage.jsx
  src/Pages/chat/chatPage/ChatPage.scss
  src/Pages/chat/chatRoom/ChatRoom.jsx
  src/Pages/chat/chatRoom/ChatRoom.scss
  src/Pages/chat/chatRoom/Chatting.jsx
  src/Pages/chat/chatRoom/GetMessage.jsx
  src/Pages/chat/chatRoom/Message.scss
  src/Pages/chat/chatRoom/SendMessage.jsx
  src/Pages/follow/Follow.scss
  src/Pages/follow/FollowUser.jsx
  src/Pages/follow/Followers.jsx
  src/Pages/follow/Followings.jsx
  src/Pages/profile/Profile.scss
  src/Pages/profile/UserProfile.jsx
Labels: cleanup

#79 🎨user info box 컴포넌트 추가 및 오타 수정
  src/Components/button/UserMoreBtn.scss
  src/Components/post/Post.jsx
  src/Components/post/Post.scss
  src/Components/user/UserInfoBox.jsx
  src/Components/user/UserInfoBox.scss
  src/Pages/home/userSearch/SearchResult.jsx
  src/Pages/home/userSearch/SearchResult.scss
  src/Pages/home/userSearch/UserSearch.scss
  src/Pages/profile/commentPage/CommentList.scss
  src/Pages/profile/commentPage/CommentPage.scss
Labels: React

#81 스플래시 애니메이션 기능 추가, primary 컬러 변경
  src/Components/splash/Logo.jsx
  src/Components/splash/Splash.jsx
  src/Components/splash/Splash.scss
  src/Components/style/_variables.scss
  src/Pages/home/homeSearch/HomeSearch.jsx
  src/Pages/home/homeSearch/HomeSearch.scss
  src/Pages/logIn/Login.jsx
  src/Pages/logIn/Login.scss
  src/Pages/logIn/LoginSection.scss
  src/assets/logo.svg
  src/assets/logo_gray.svg
  src/assets/logo_purple.svg
Labels: function, css

#83 🧹 기본 프로필이미지 url 변경
  src/Pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/assets/profile.png
Labels: docs

#90 🔧 NotFound 페이지 구현
  src/App.jsx
  src/Pages/notFound/NotFound.jsx
  src/Pages/notFound/NotFound.scss
Labels: function, css, React

#97 🎨 footer 포커스시 텍스트 color 변환, 버튼 커서 포인터 추가
  src/assets/icon-profile-small.svg
  src/components/footer/CommentFooter.jsx
  src/components/footer/MainFooter.scss
  src/components/footer/PageFooter.scss
  src/components/footer/TabmenuList.jsx
  src/components/footer/TabmenuList.scss
  src/components/style/reset.scss
Labels: Html, css, React

#100 🎨: UploadPost 페이지 레이아웃, 스타일 수정
  src/assets/icon-x.svg
  src/pages/uploadPost/PhotoList.jsx
  src/pages/uploadPost/PhotoList.scss
  src/pages/uploadPost/UploadPost.jsx
  src/pages/uploadPost/UploadPost.scss
Labels: Html, css, React

#101 마이페이지 데이터 불러오기 기능, context 파일명 변경, 변수명 변경
  src/App.jsx
  src/components/splash/Logo.jsx
  src/components/user/UserInfoBox.scss
  src/context/LoginContext.jsx
  src/context/UserContext.jsx
  src/pages/home/Home.jsx
  src/pages/logIn/emailLogin/EmailLogin.jsx
  src/pages/profile/MyProfile.jsx
  src/pages/profile/Profile.scss
  src/pages/profile/UserProfile.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
  src/pages/profile/profileHeader/ProfileHeader.scss
Labels: function, React

#102 🔧 유저프로필 url로 접근시 데이터 불러오기 기능 추가, invalid 계정일시에 Not Found
  package-lock.json
  package.json
  src/App.jsx
  src/assets/logo_404.svg
  src/assets/logo_loading.svg
  src/pages/logIn/emailLogin/EmailLogin.jsx
  src/pages/logIn/signUp/SignUp.jsx
  src/pages/notFound/NotFound.jsx
  src/pages/notFound/NotFound.scss
  src/pages/profile/MyProfile.jsx
  src/pages/profile/Profile.scss
  src/pages/profile/UserProfile.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
Labels: function, React

#106 🔧 검색기능구현 추가. 추후 이미지, useContext추가 및 scss 수정 예정
  src/components/header/SearchHeader.jsx
  src/components/user/UserInfoBox.scss
  src/pages/home/userSearch/SearchResult.jsx
  src/pages/home/userSearch/UserSearch.jsx
Labels: function

#108 🔧 팔로잉, 팔로우 기능 구현
  src/App.jsx
  src/components/button/FollowBtn.jsx
  src/components/button/FollowBtn.scss
  src/components/footer/MainFooter.jsx
  src/components/user/UserInfoBox.jsx
  src/pages/chat/chatRoom/GetMessage.jsx
  src/pages/follow/Follow.scss
  src/pages/follow/FollowUser.jsx
  src/pages/follow/Followers.jsx
  src/pages/follow/Followings.jsx
  src/pages/home/userSearch/SearchResult.jsx
  src/pages/logIn/emailLogin/EmailLogin.jsx
  src/pages/logIn/signUp/SignUp.jsx
  src/pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/pages/logIn/signUp/profileSet/UploadPic.jsx
  src/pages/profile/MyProfile.jsx
  src/pages/profile/UserProfile.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
Labels: function, React

#109 🔧사용자 피드에서 판매상품 목록 구현 기능 추가
  src/pages/home/userSearch/UserSearch.jsx
  src/pages/profile/MyProfile.jsx
  src/pages/profile/UserProfile.jsx
  src/pages/profile/userProduct/Product.jsx
  src/pages/profile/userProduct/UserProduct.jsx
  src/pages/profile/userProduct/UserProduct.scss
Labels: function

#111 ♻️ 유저, 마이 프로필 페이지 컴포넌트화
  src/App.jsx
  src/context/UserContext.jsx
  src/pages/home/userSearch/SearchResult.jsx
  src/pages/home/userSearch/UserSearch.jsx
  src/pages/logIn/emailLogin/EmailLogin.jsx
  src/pages/logIn/signUp/profileSet/UploadPic.jsx
  src/pages/profile/MyProfile.jsx
  src/pages/profile/Profile.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
  src/pages/profile/userPost/UserPost.jsx
  src/pages/profile/userProduct/UserProduct.jsx
Labels: refactoring, cleanup, React

#112 ♻️ 팔로잉,팔로우 코드 리팩토링, 🔧 프로필,피드 포스트 불러오기 기능 구현
  src/App.jsx
  src/components/button/CommentBtn.jsx
  src/components/button/LikeBtn.jsx
  src/components/button/UserMoreBtn.scss
  src/components/post/Post.jsx
  src/components/post/Post.scss
  src/components/post/PostList.jsx
  src/components/user/UserInfoBox.scss
  src/pages/follow/FollowList.jsx
  src/pages/follow/Followers.jsx
  src/pages/follow/Followings.jsx
  src/pages/follow/User.jsx
  src/pages/follow/UserList.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.scss
  src/pages/home/homeSearch/HomeSearch.scss
  src/pages/profile/Profile.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
  src/pages/profile/userPost/UserPost.jsx
  src/pages/profile/userPost/UserPost.scss
Labels: refactoring, cleanup, function, React

#113 🧹 로딩 이미지 변경, alt값 변경
  src/App.jsx
  src/assets/logo_loading_purple.svg
  src/components/button/LikeBtn.jsx
  src/pages/follow/FollowList.jsx
  src/pages/follow/User.jsx
  src/pages/home/Home.jsx
  src/pages/home/userSearch/UserSearch.jsx
  src/pages/profile/Profile.jsx
Labels: React

#115 🔧 포스트 앨범뷰,리스트뷰 기능 구현
  src/pages/profile/userPost/UserPost.jsx
  src/pages/profile/userPost/UserPost.scss
Labels: function, React

#116 🔧 포스트 상세페이지 구현
  src/App.jsx
  src/components/button/CommentBtn.jsx
  src/components/post/Article.jsx
  src/components/post/Post.jsx
  src/pages/profile/commentPage/CommentPage.jsx
Labels: function, React

#117 🔧 포스트 댓글 데이터 불러오기 구현
  src/components/post/Article.jsx
  src/pages/profile/commentPage/Comment.jsx
  src/pages/profile/commentPage/CommentList.jsx
  src/pages/profile/commentPage/CommentList.scss
  src/pages/profile/commentPage/CommentPage.jsx
Labels: React

#118 🐞이전 페이지의 판매상품 리스트가 현재 페이지에 나타나는 문제 수정
  src/components/button/SaveBtn.jsx
  src/components/header/UploadHeader.jsx
  src/pages/profile/userProduct/Product.jsx
  src/pages/profile/userProduct/UserProduct.jsx
  src/pages/uploadPost/UploadPost.jsx
Labels: bug

#120 🔧 : 프로필 수정기능 구현 및 Splash 세션 스토리지 사용으로 변경
  src/App.jsx
  src/components/button/SaveBtn.jsx
  src/components/header/SaveHeader.jsx
  src/components/splash/Splash.jsx
  src/context/SplashContext.jsx
  src/pages/home/Home.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/pages/profileEdit/ProfileEditInfo.jsx
Labels: function, React

#122 🔧: 프로필 수정 시 로컬스토리지에 accountname 수정
  src/pages/profileEdit/ProfileEdit.jsx
Labels: React

#123 🔧 페이지별로 모달창 적용
  public/index.html
  src/components/button/MoreBtn.jsx
  src/components/button/UserMoreBtn.jsx
  src/components/header/ChatRoomHeader.jsx
  src/components/header/CommonHeader.jsx
  src/components/modal/Modal.scss
  src/components/modal/common/ModalButton.jsx
  src/components/modal/common/ModalFrame.jsx
  src/components/modal/common/ModalPortal.jsx
  src/components/modal/contents/CommentModal.jsx
  src/components/modal/contents/DefaultModal.jsx
  src/components/modal/contents/PostModal.jsx
  src/components/modal/contents/ProductModal.jsx
  src/components/modal/contents/QuitChatModal.jsx
  src/components/post/Article.jsx
  src/pages/chat/chatPage/ChatPage.jsx
  src/pages/chat/chatRoom/ChatRoom.jsx
  src/pages/profile/Profile.jsx
  src/pages/profile/commentPage/Comment.jsx
  src/pages/profile/commentPage/CommentPage.jsx
  src/pages/profile/userProduct/Product.jsx
  src/pages/profile/userProduct/UserProduct.scss
Labels: React

#124 🧹: 프로필수정 할때 이미지만 변경 가능하게 수정했습니다.
  src/pages/profileEdit/ProfileEdit.jsx
  src/pages/profileEdit/ProfileEditInfo.jsx
Labels: function, React

#125 🔧 이미지 예외처리 기능 Context 컴포넌트화 및 적용
  src/App.jsx
  src/components/footer/CommentFooter.jsx
  src/components/footer/PageFooter.scss
  src/context/ImageTestContext.jsx
  src/pages/follow/FollowList.jsx
  src/pages/follow/User.jsx
  src/pages/follow/UserList.jsx
  src/pages/home/Home.jsx
  src/pages/logIn/signUp/SignUp.jsx
  src/pages/logIn/signUp/emailSignUp/EditAccount.jsx
  src/pages/logIn/signUp/emailSignUp/EmailSignUp.jsx
  src/pages/logIn/signUp/profileSet/EditInfo.jsx
  src/pages/logIn/signUp/profileSet/ProfileSet.jsx
  src/pages/logIn/signUp/profileSet/UploadPic.jsx
  src/pages/profile/Profile.jsx
  src/pages/profile/commentPage/Comment.jsx
  src/pages/profile/commentPage/CommentList.jsx
  src/pages/profile/commentPage/CommentPage.jsx
  src/pages/profile/profileHeader/ProfileHeader.jsx
  src/pages/profile/userPost/UserPost.jsx
Labels: cleanup, React

#129 🐞 이미지 검증에 걸러지지 않는 엑박 이미지 예외처리
  src/assets/image_error.png
  src/components/post/Article.jsx
  src/context/ImageTestContext.jsx
  src/pages/searchUserPage/searchResult/SearchResult.jsx
Labels: fix

#132 📁: 컨벤션에 맞게 폴더 트리 및 import 순서 변경
  src/App.jsx
  src/components/footer/CommentFooter.jsx
  src/components/footer/MainFooter.jsx
  src/components/post/Post.jsx
  src/components/splash/Splash.jsx
  src/components/splash/logo/Logo.jsx
  src/pages/profileEditPage/ProfileEdit.jsx
  src/pages/profileEditPage/ProfileEdit.scss
  src/pages/profileEditPage/profileEditImg/ProfileEditImg.jsx
  src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
Labels: cleanup

#131 🔧 url 예외처리 기능 추가, 라우터 경로 변경
  src/App.jsx
  src/pages/followPage/FollowPage.jsx
  src/pages/notFound/NotFound.jsx
  src/pages/notFound/NotFound.scss
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/postDetailPage/PostDetailPage.scss
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/userHeader/UserHeader.jsx
  src/pages/profilePage/userPost/UserPost.jsx
Labels: fix, function, React

#133 🧹 모달창,알람창 적용 및 수정
  src/components/header/ChatRoomHeader.jsx
  src/components/header/CommonHeader.jsx
  src/components/modal/alert/alertBase/AlertBtn.jsx
  src/components/modal/alert/alertBase/AlertFrame.jsx
  src/components/modal/alert/alertBase/CancelBtn.jsx
  src/components/modal/alert/alerts/DeleteAlert.jsx
  src/components/modal/alert/alerts/LogoutAlert.jsx
  src/components/modal/alert/alerts/QuitChatAlert.jsx
  src/components/modal/alert/alerts/ReportAlert.jsx
  src/components/modal/alert/common/CancelBtn.jsx
  src/components/modal/common/ModalButton.jsx
  src/components/modal/contents/CommentModal.jsx
  src/components/modal/contents/DefaultModal.jsx
  src/components/modal/contents/PostModal.jsx
  src/components/modal/contents/ProductModal.jsx
  src/components/modal/contents/QuitChatModal.jsx
  src/components/modal/modalBase/ModalBtn.jsx
  src/components/modal/modalBase/ModalFrame.jsx
  src/components/modal/modalBase/ModalPortal.jsx
  src/components/modal/modals/CommentModal.jsx
  src/components/modal/modals/DefaultModal.jsx
  src/components/modal/modals/PostModal.jsx
  src/components/modal/modals/ProductModal.jsx
  src/components/modal/modals/QuitChatModal.jsx
  src/components/post/Article.jsx
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/userProduct/Product.jsx
Labels: React

#134 🔧 스크롤시에 댓글 데이터 추가요청 기능 추가
  src/components/footer/CommentFooter.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
Labels: function, React

#136 🧹 포스트 댓글 빈값 요청 이슈, 유효성 ui 추가
  src/components/footer/CommentFooter.jsx
Labels: css, React

#137 🐞 스플래시 화면 멈추는 이슈 수정
  src/assets/logo_loading.svg
  src/assets/logo_loading_purple.svg
  src/components/post/Article.jsx
  src/components/splash/Splash.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/userPost/UserPost.scss
  src/pages/signUpPage/profileSet/EditInfo.jsx
  src/pages/signUpPage/profileSet/UploadImg.jsx
Labels: fix

#138 🔧게시물 업로드에 사진 업로드 기능 추가
  src/components/button/UploadIconBtn.jsx
  src/pages/uploadPostPage/ImgFilePreview.jsx
  src/pages/uploadPostPage/UploadPostPage.jsx
  src/pages/uploadPostPage/previewImgList/PreviewImgList.jsx
  src/pages/uploadPostPage/previewImgList/PreviewImgList.scss
Labels: function

#141 🔧 : 상품등록 페이지 기능 구현, 프로필 수정 페이지 수정, 리드미 추가 #140
  README.md
  src/App.jsx
  src/pages/profileEditPage/ProfileEditPage.jsx
  src/pages/profileEditPage/ProfileEditPage.scss
  src/pages/profilePage/userHeader/UserHeader.jsx
  src/pages/uploadProductPage/UploadProductPage.jsx
  src/pages/uploadProductPage/UploadProductPage.scss
  src/pages/uploadProductPage/uploadProductImg/UploadProductImg.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: function, css, React

#143 🎨게시물 업로드 기능 오류 수정 및 pending시 사용자 프로필 이미지 기본 이미지 설정, 이미지 미리보기 UI 수정
  src/components/button/LikeBtn.jsx
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/uploadPostPage/UploadPostPage.jsx
  src/pages/uploadPostPage/UploadPostPage.scss
  src/pages/uploadPostPage/previewImgList/PreviewImgList.scss
Labels: fix, function, css

#144 🧹 토큰 없이 서버에 요청 보내는 이슈 수정
  src/App.jsx
  src/context/UserContext.jsx
  src/pages/emailLoginPage/EmailLoginPage.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
  src/pages/signUpPage/profileSet/EditInfo.jsx
Labels: fix, React

#147 🔧 좋아요 버튼 기능 구현 완료
  src/components/button/LikeBtn.jsx
  src/components/post/Article.jsx
Labels: function

#148 🔧 상품 신고 삭제 기능 구현, 채팅목록 채팅방 내용 수정
  src/App.jsx
  src/components/modal/alert/alerts/DeleteAlert.jsx
  src/components/modal/modalBase/ModalFrame.jsx
  src/components/modal/modals/CommentModal.jsx
  src/components/modal/modals/ProductModal.jsx
  src/components/user/UserInfoBox.scss
  src/pages/chatPage/ChatPage.jsx
  src/pages/chatPage/chatPageItem/ChatItem.jsx
  src/pages/chatRoomPage/ChatRoomPage.jsx
  src/pages/chatRoomPage/ChatRoomPage.scss
  src/pages/chatRoomPage/chatRoomInput/Chatting.jsx
  src/pages/chatRoomPage/chatRoomInput/GetMessage.jsx
  src/pages/chatRoomPage/chatRoomInput/Message.scss
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/profilePage/userProduct/UserProduct.jsx
  src/pages/uploadProductPage/UploadProductPage.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: function, css

#149 🔧: 프로필 수정페이지 데이터 가져오는 방식 변경
  src/pages/profileEditPage/ProfileEditPage.jsx
  src/pages/profilePage/userHeader/UserHeader.jsx
Labels: function, React

#153 📝 리드미 내용 추가 및 수정
  README.md
Labels: docs

#151 🧹 댓글 infinite scroll 요청개수 수정 및 pending 관리 state 이름 변경
  src/pages/followPage/FollowPage.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/ProfilePage.jsx
Labels: fix, cleanup

#155 상품 웹사이트 기본 인풋값, 불필요한 코드 제거, 수정페이지 생성, 라우트 추가
  README.md
  src/App.jsx
  src/components/modal/modals/CommentModal.jsx
  src/components/modal/modals/PostModal.jsx
  src/components/modal/modals/ProductModal.jsx
  src/pages/chatRoomPage/ChatRoomPage.jsx
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/updateProductPage/UpdateProductPage.jsx
  src/pages/updateProuctPage/UpdateProductPage.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: docs, cleanup, function

#156 🔧게시물 업로드 시 미리보기 이미지 삭제 후 같은 이미지 파일 업로드 되도록 수정
  package-lock.json
  package.json
  src/pages/uploadPostPage/UploadPostPage.jsx
Labels: function

#157 게시글 , 상품 수정 기능 구현
  src/App.jsx
  src/components/modal/alert/alerts/DeleteAlert.jsx
  src/components/modal/modals/CommentModal.jsx
  src/components/modal/modals/DefaultModal.jsx
  src/components/modal/modals/PostModal.jsx
  src/components/modal/modals/ProductModal.jsx
  src/components/post/Article.jsx
  src/components/post/Post.jsx
  src/components/post/PostList.jsx
  src/hooks/useDelete.jsx
  src/hooks/useReport.jsx
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/userPost/UserPost.jsx
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/profilePage/userProduct/UserProduct.jsx
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/updateProductPage/UpdateProductPage.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: function, React

#158 🔧게시물 업로드에서 이미지 미리보기 삭제 시 input value 초기화
  src/components/button/UploadIconBtn.jsx
  src/pages/uploadPostPage/UploadPostPage.jsx
Labels: function

#161 🔧 모든 무한스크롤 기능 추가, 페이지 이동시 스크롤 제일 위로 오게
  src/App.jsx
  src/pages/emailLoginPage/EmailLoginPage.jsx
  src/pages/followPage/FollowPage.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/userPost/UserPost.jsx
  src/pages/profilePage/userPost/UserPost.scss
  src/scrollRestoration/ScrollToTop.jsx
Labels: function, React

#160 Follow 컴포넌트 ui 개선, 인풋 포커징 기능 추가
  src/components/footer/CommentFooter.jsx
  src/components/modal/modalBase/ModalLink.jsx
  src/components/user/UserInfoBox.scss
  src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
  src/pages/profilePage/userProduct/UserProduct.jsx
  src/pages/signUpPage/emailSignUp/EditAccount.jsx
  src/pages/signUpPage/profileSet/EditInfo.jsx
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/updateProductPage/UpdateProductPage.jsx
  src/pages/uploadPostPage/UploadPostPage.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: function, css, React

#162 🔧 포스트 앨범뷰 데이터 받아오기 및 UI 구현
  src/assets/iccon-img-layers.svg
  src/pages/profilePage/userPost/PostAlbum.jsx
  src/pages/profilePage/userPost/UserPost.jsx
  src/pages/profilePage/userPost/UserPost.scss
Labels: css, React

#164 🔧 댓글,포스트 -분전 기능 추가
  src/components/post/Article.jsx
  src/pages/postDetailPage/comment/Comment.jsx
Labels: function, React

#165 게시글 이미지 수정기능 개선 및 추가 구현, 버튼 활성화 UI 적용, 기타 CSS 수정
  src/components/button/FollowBtn.scss
  src/components/button/ProfileButton.scss
  src/components/modal/Modal.scss
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: function, css, React

#166 🔧 무한스크롤 로딩 UI추가 및 스크롤 중복데이터 오류 수정
  src/assets/icon-loading.svg
  src/components/post/Article.jsx
  src/components/post/Post.scss
  src/pages/followPage/FollowPage.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/userPost/UserPost.jsx
  src/pages/profilePage/userPost/UserPost.scss
Labels: fix, function, css, React

#167 🔧: 이미지 Swiper 기능 추가 및 리드미 수정
  README.md
  package-lock.json
  package.json
  src/components/post/Article.jsx
  src/components/post/Post.scss
Labels: docs, function, css, React

#168 🎨 모바일 대응 css 적용 , 버튼 스타일 수정
  public/index.html
  src/components/button/FollowBtn.scss
  src/components/button/ProfileButton.scss
  src/components/style/reset.scss
Labels: css

#169 ♻️ 이미지 테스트 context -> hooks로 변경
  src/App.jsx
  src/components/footer/CommentFooter.jsx
  src/components/post/Article.jsx
  src/context/ImageTestContext.jsx
  src/context/ProfileTestContext.jsx
  src/hooks/useImageTest.jsx
  src/hooks/useProfileImageTest.jsx
  src/pages/followPage/followList/User.jsx
  src/pages/profilePage/userHeader/UserHeader.jsx
  src/pages/profilePage/userPost/PostAlbum.jsx
  src/pages/searchUserPage/searchResult/SearchResult.jsx
Labels: refactoring

#170 🎨: 이미지 Swiper UI 수정
  src/components/post/Article.jsx
  src/components/post/Post.scss
Labels: refactoring, css

#171 🧹 댓글 실시간 코멘트 count up 기능 추가
  src/components/footer/CommentFooter.jsx
Labels: function

#172 🧹 프로필 에러이미지 적용 안된 컴포넌트 수정
  src/components/post/Article.jsx
  src/hooks/useProfileImageTest.jsx
  src/pages/followPage/followList/User.jsx
  src/pages/profilePage/userHeader/UserHeader.jsx
  src/pages/searchUserPage/searchResult/SearchResult.jsx
Labels: React

#173 모달 컴포넌트 변경 및 적용, 게시글 수정 기존 데이터 누락 수정, input css 수정
  src/components/header/ChatRoomHeader.jsx
  src/components/header/CommonHeader.jsx
  src/components/modal/Alert.jsx
  src/components/modal/Alert.scss
  src/components/modal/Modal.jsx
  src/components/modal/Modal.scss
  src/components/modal/ModalPortal.jsx
  src/components/modal/alert/alertBase/AlertBtn.jsx
  src/components/modal/alert/alertBase/AlertFrame.jsx
  src/components/modal/alert/alertBase/CancelBtn.jsx
  src/components/modal/alert/alerts/DeleteAlert.jsx
  src/components/modal/alert/alerts/LogoutAlert.jsx
  src/components/modal/alert/alerts/QuitChatAlert.jsx
  src/components/modal/alert/alerts/ReportAlert.jsx
  src/components/modal/modalBase/ModalBtn.jsx
  src/components/modal/modalBase/ModalFrame.jsx
  src/components/modal/modalBase/ModalLink.jsx
  src/components/modal/modals/CommentModal.jsx
  src/components/modal/modals/DefaultModal.jsx
  src/components/modal/modals/PostModal.jsx
  src/components/modal/modals/ProductModal.jsx
  src/components/modal/modals/QuitChatModal.jsx
  src/components/post/Article.jsx
  src/components/style/reset.scss
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/updatePostPage/UpdatePostPage.jsx
Labels: refactoring, css, React

#174 🎨 판매중인 상품 이미지 border 추가 및 이미지 사이즈 맞춤 조정
  package-lock.json
  package.json
  src/pages/profilePage/userProduct/UserProduct.scss
Labels: css

#175 🧹 profileImageTest 반영되지 않은 오류 해결
  .firebase/hosting.YnVpbGQ.cache
  .firebaserc
  firebase.json
  src/components/footer/CommentFooter.jsx
Labels: fix

#176 게시글 수정 페이지, notFound 페이지 개선
  src/components/notFound/NotFound.jsx
  src/components/notFound/NotFound.scss
  src/pages/updatePostPage/UpdatePostPage.jsx
Labels: function, css

#177 🧹 코멘트페이지 프로필 에러이미지 예외처리 적용
  .firebase/hosting.YnVpbGQ.cache
  src/pages/postDetailPage/comment/Comment.jsx
Labels: React

#178 🎨 수정 페이지 pending, rejected 상태 추가
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/updateProductPage/UpdateProductPage.jsx
Labels: css

#179 🔧: 프로필 수정 페이지 상태별 화면 로드 기능 추가, 상품등록 페이지 rejected 상태 화면 추가
  src/pages/profileEditPage/ProfileEditPage.jsx
  src/pages/uploadProductPage/UploadProductPage.jsx
Labels: function, React

#180 🔧세션스토리지를 사용하여 뒤로가기로 유저검색창 이동시 검색결과 유지
  src/components/header/SearchHeader.jsx
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/searchUserPage/SearchUserPage.jsx
  src/pages/searchUserPage/searchResult/SearchResult.jsx
Labels: function

#181 로그인 페이지 useContext token 적용, import 순서 변경
  src/hooks/useDelete.jsx
  src/hooks/useReport.jsx
  src/pages/emailLoginPage/EmailLoginPage.jsx
Labels: React

#183 🧹 app.jsx 개행 컨벤션 수정
  src/App.jsx
Labels: cleanup

#185 로그인 토큰 수정 , 상품 등록 이미지, 가격 제한
  src/pages/emailLoginPage/EmailLoginPage.jsx
  src/pages/uploadProductPage/uploadProductImg/UploadProductImg.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: React

#184 🧹 상품 컴포넌트 UI 수정
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/profilePage/userProduct/UserProduct.scss
Labels: css

#182 🔧판매중인 상품 가격 표시 예외처리 추가
  src/pages/profilePage/userProduct/Product.jsx
Labels: fix, function

#186 🧹 모바일 border-radius 안먹는 이슈 수정
  src/components/button/FollowBtn.scss
  src/pages/postDetailPage/comment/CommentList.scss
  src/pages/profilePage/userHeader/UserHeader.scss
  src/pages/profilePage/userPost/UserPost.scss
  src/pages/profilePage/userProduct/UserProduct.scss
Labels: css

#187 🧹 useEffect 의존배열 필요없는 코드 삭제
  src/pages/followPage/FollowPage.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/userPost/PostAlbum.jsx
  src/pages/profilePage/userPost/UserPost.jsx
  src/pages/profilePage/userProduct/UserProduct.jsx
  src/pages/signUpPage/SignUpPage.jsx
  src/pages/signUpPage/profileSet/EditInfo.jsx
  src/pages/updatePostPage/UpdatePostPage.jsx
Labels: cleanup

#189 🧹 상품 가격 limit 문구 추가 , 모든 인풋 입력시 업로드 버튼 활성화
  src/pages/uploadProductPage/UploadProductPage.jsx
  src/pages/uploadProductPage/UploadProductPage.scss
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: css, React

#188 ♻️ imageTest hook 중복코드 삭제
  src/components/footer/CommentFooter.jsx
  src/components/post/Article.jsx
  src/hooks/useImageTest.jsx
  src/hooks/useProfileImageTest.jsx
  src/pages/followPage/followList/User.jsx
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/profilePage/userHeader/UserHeader.jsx
  src/pages/profilePage/userPost/PostAlbum.jsx
  src/pages/profilePage/userProduct/Product.jsx
  src/pages/searchUserPage/searchResult/SearchResult.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: cleanup, React

#190 🧹 handleChange 함수 중복코드 수정
  src/pages/emailLoginPage/EmailLoginPage.jsx
  src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
  src/pages/signUpPage/emailSignUp/EditAccount.jsx
  src/pages/signUpPage/profileSet/EditInfo.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
Labels: cleanup

#191 🔧 회원가입시 자동 로그인 기능 추가
  src/App.jsx
  src/components/button/FollowBtn.jsx
  src/components/header/Header.scss
  src/components/modal/Alert.scss
  src/components/modal/Modal.scss
  src/components/post/Article.jsx
  src/components/post/Post.scss
  src/context/UserContext.jsx
  src/pages/chatPage/ChatPage.scss
  src/pages/chatRoomPage/chatRoomInput/Message.scss
  src/pages/emailLoginPage/EmailLoginPage.jsx
  src/pages/followPage/FollowPage.jsx
  src/pages/followPage/FollowPage.scss
  src/pages/followPage/followList/User.jsx
  src/pages/followPage/followList/UserList.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/logInPage/userAccount/UserAccount.scss
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/userHeader/UserHeader.jsx
  src/pages/profilePage/userPost/PostAlbum.jsx
  src/pages/profilePage/userPost/UserPost.jsx
  src/pages/signUpPage/SignUpPage.jsx
  src/pages/signUpPage/emailSignUp/EmailSignUp.jsx
  src/pages/signUpPage/profileSet/ProfileSet.jsx
Labels: cleanup, React

#192 🧹 상품 수정페이지 오류 수정
  src/pages/updateProductPage/UpdateProductPage.jsx
  src/pages/uploadProductPage/uploadProductImg/UploadProductImg.jsx
Labels: React

#193 🧹 삭제 후 리렌더링 안되던 문제 해결, 콘솔 오류 제거 , 무한 렌더링 제거, 변수명 변경
  README.md
  src/components/header/ChatRoomHeader.jsx
  src/components/header/CommonHeader.jsx
  src/components/modal/Alert.jsx
  src/components/modal/Modal.jsx
  src/components/post/Article.jsx
  src/components/post/Post.jsx
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/userProduct/Product.jsx
Labels: React

#194 🧹유저검색페이지, 프로필 페이지에서 긴 유저네임 예외처리
  src/components/user/UserInfoBox.scss
  src/pages/profilePage/userHeader/UserHeader.scss
  src/pages/searchUserPage/searchResult/SearchResult.jsx
  src/pages/uploadPostPage/previewImgList/PreviewImgList.jsx
Labels: fix

#195 🐞 프로필 이동시 헤더 변경되지 않는 오류 수정
  src/components/button/BackBtn.jsx
  src/components/button/BackBtn.scss
  src/components/button/CommentBtn.jsx
  src/components/button/FollowBtn.jsx
  src/components/button/LikeBtn.jsx
  src/components/button/LoginButton.jsx
  src/components/button/MoreBtn.scss
  src/components/button/SaveBtn.jsx
  src/components/button/SearchBtn.jsx
  src/components/button/SearchBtn.scss
  src/components/button/UploadIconBtn.jsx
  src/components/footer/CommentFooter.jsx
  src/components/footer/TabmenuList.jsx
  src/components/header/ChatRoomHeader.jsx
  src/components/header/CommonHeader.jsx
  src/components/header/UploadHeader.jsx
  src/components/notFound/NotFound.jsx
  src/components/post/Article.jsx
  src/components/post/Post.jsx
  src/components/splash/logo/Logo.jsx
  src/components/user/UserInfoBox.jsx
  src/context/UserContext.jsx
  src/hooks/useDelete.jsx
  src/hooks/useImageTest.jsx
  src/pages/emailLoginPage/EmailLoginPage.jsx
  src/pages/followPage/FollowPage.jsx
  src/pages/followPage/followList/User.jsx
  src/pages/followPage/followList/UserList.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/postDetailPage/PostDetailPage.jsx
  src/pages/postDetailPage/comment/Comment.jsx
  src/pages/postDetailPage/comment/CommentList.jsx
  src/pages/profileEditPage/profileEditImg/ProfileEditImg.jsx
  src/pages/profileEditPage/profileEditInfo/ProfileEditInfo.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/searchUserPage/SearchUserPage.scss
  src/pages/signUpPage/SignUpPage.jsx
  src/pages/signUpPage/emailSignUp/EditAccount.jsx
  src/pages/signUpPage/profileSet/EditInfo.jsx
  src/pages/signUpPage/profileSet/ProfileSet.jsx
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/updateProductPage/UpdateProductPage.jsx
  src/pages/uploadPostPage/previewImgList/PreviewImgList.jsx
  src/pages/uploadProductPage/UploadProductPage.jsx
  src/pages/uploadProductPage/uploadProductImg/UploadProductImg.jsx
  src/pages/uploadProductPage/uploadProductInput/UploadProductInput.jsx
  src/scrollRestoration/ScrollToTop.jsx
Labels: cleanup, React

#196 🧹 삭제 리렌더링 hook 수정, 리드미 수정
  README.md
  src/hooks/useDelete.jsx
Labels: docs, fix

#197 🧹 팔로우페이지 초기 로드 20명으로 수정
  README.md
  src/pages/followPage/FollowPage.jsx
Labels: React

#198 🎨게시물 등록 및 수정페이지 유저 프로필 이미지 css 수정
  src/pages/updatePostPage/UpdatePostPage.jsx
  src/pages/uploadPostPage/UploadPostPage.jsx
  src/pages/uploadPostPage/UploadPostPage.scss
Labels: css

#199 🔧 피드 페이지 최상단 이동 기능 추가
  src/components/footer/CommentFooter.jsx
  src/pages/homePage/HomePage.jsx
  src/pages/homePage/HomePage.scss
  src/pages/profileEditPage/ProfileEditPage.jsx
Labels: function, css, React

#200 🧹 scroll-top 버튼 스타일 코드 수정
  src/assets/scroll-top.svg
  src/pages/homePage/HomePage.scss
Labels: css

#201 🔧 댓글 작성후에도 무한스크롤 동작하도록 수정
  src/pages/postDetailPage/comment/CommentList.jsx
Labels: React

#203 🔧 댓글 삭제 시 댓글 수 카운트다운 구현, 파비콘 등록
  README.md
  public/favicon.ico
  public/index.html
  src/hooks/useDelete.jsx
Labels: function
